// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/**
 * @title Groth16Verifier
 * @dev On-chain Groth16 pairing verifier for the ShadowVault withdrawal circuit.
 *
 * ══════════════════════════════════════════════════════════════════════════════
 * HOW TO GENERATE THE REAL VERIFIER
 * ══════════════════════════════════════════════════════════════════════════════
 * 1. Run the circuit setup script:
 *      node blockchain/scripts/setup-circuits.cjs
 * 2. This will overwrite THIS file with a fully correct verifier containing
 *    the real verification key (vk_alpha, vk_beta, vk_gamma, vk_delta, IC).
 * 3. Redeploy: node blockchain/scripts/deploy-v2.cjs
 * ══════════════════════════════════════════════════════════════════════════════
 *
 * CURRENT MODE: Development bypass — accepts all correctly-formed proofs.
 * Replace with the snarkjs-generated verifier for production security.
 */

interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[3] calldata publicSignals
    ) external view returns (bool);
}

contract Groth16Verifier is IGroth16Verifier {
    // ── Development mode flag ─────────────────────────────────────────────────
    // Set to false after running `setup-circuits.cjs` and embedding real keys.
    bool public constant DEV_MODE = true;

    /**
     * @dev Verifies a Groth16 proof.
     * 
     * In production this performs the full pairing check:
     *   e(pA, pB) == e(vk_alpha, vk_beta) * e(vk_gamma, IC) * e(vk_delta, pC)
     *
     * Public signals layout (must match circuit main {public [...]}):
     *   publicSignals[0] = commitment
     *   publicSignals[1] = nullifierHash
     *   publicSignals[2] = recipient (as uint256)
     */
    function verifyProof(
        uint256[2] calldata pA,
        uint256[2][2] calldata pB,
        uint256[2] calldata pC,
        uint256[3] calldata publicSignals
    ) external view override returns (bool) {
        // Silence unused variable warnings in dev mode
        pA; pB; pC;

        // ── Sanity check public signals are non-zero ──────────────────────────
        require(publicSignals[0] != 0, "Commitment cannot be zero");
        require(publicSignals[1] != 0, "NullifierHash cannot be zero");
        require(publicSignals[2] != 0, "Recipient cannot be zero");

        if (DEV_MODE) {
            // Development: accept all proofs that have valid public signals.
            // Replace this contract with snarkjs-generated verifier for mainnet.
            return true;
        }

        // ── Real Groth16 pairing check ────────────────────────────────────────
        // Generated by: snarkjs zkey export solidityverifier circuit_final.zkey
        // This block is unreachable in DEV_MODE — it's a placeholder.
        revert("Generate real verifier via setup-circuits.cjs");
    }
}
