import { NextRequest, NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

export async function POST(req: NextRequest) {
    try {
        const formData = await req.formData();
        const file = formData.get("file") as File;

        if (!file) {
            return NextResponse.json({ error: "No document file provided" }, { status: 400 });
        }

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            console.error("GEMINI_API_KEY is not configured.");
            return NextResponse.json({ error: "Gemini API key is not configured on the server." }, { status: 500 });
        }

        const ai = new GoogleGenAI({ apiKey: apiKey });

        const bytes = await file.arrayBuffer();
        const base64Doc = Buffer.from(bytes).toString("base64");

        // Use the official mime type provided by the file, or fallback to pdf if unknown
        const mimeType = file.type || "application/pdf";

        const prompt = `
        You are an expert digital forensics analyst and fraud investigator working for a government agency.
        Your job is to analyze the attached document (which was submitted as evidence in a whistleblower or civic complaint case) and determine if it is trustworthy or if it exhibits signs of being fake, AI-generated, or heavily manipulated.
        
        Do NOT summarize the document. DO NOT provide a "trust score".
        
        Instead, look for:
        1. Linguistic & Tone Analysis: Does it read like an overly verbose, hallucinated, or highly-structured ChatGPT response?
        2. Internal Consistency: Are there conflicting dates, misaligned financial figures, or logical flaws in the events described?
        3. Structural Logic: Does it fail to match the standard format/jargon of the type of document it claims to be?
        
        If the document looks like a genuine, human-created complaint, report, or piece of evidence, mark it as valid. If it looks fake, autogenerated, or heavily manipulated, mark it as invalid.
        
        Respond with ONLY a strict JSON object (do not use markdown formatting tags). The JSON must have the following structure:
        {
            "isValid": boolean
        }
        `;

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [
                prompt,
                {
                    inlineData: {
                        data: base64Doc,
                        mimeType: mimeType,
                    },
                },
            ],
            config: {
                responseMimeType: "application/json",
            }
        });

        const rawText = response.text || "{}";
        
        try {
            const result = JSON.parse(rawText);
            return NextResponse.json(result);
        } catch (parseError) {
            console.error("Failed to parse Gemini response:", rawText);
            return NextResponse.json({ error: "Invalid response format from AI" }, { status: 500 });
        }

    } catch (error: any) {
        console.error("Gemini Document Verification Error:", error);
        return NextResponse.json({ error: "Failed to verify document with AI", details: error.message }, { status: 500 });
    }
}
